---
- name: setting
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: main.cf set
      template:
        src: "etc/postfix/main.cf"
        dest: /etc/postfix/main.cf
        owner: root
        group: root
        mode: 0644
        backup: true
