route:
  receiver: 'email'
  routes:
    - receiver: 'slack'
      continue: true

receivers:
  - name: 'email'
    email_configs:
      - to: 'team@example.com'
        send_resolved: true
  - name: 'slack'
    slack_configs:
      - channel: '#alerts'
        api_url: '${SLACK_WEBHOOK_URL}'
        send_resolved: true