---
- name: github self host runner setting
  hosts:
    - raspi.abe365.org
    - rasdev.abe365.org
#    - ranko.abe365.org
#    - sae.abe365.org
#    - kaede.abe365.org
#    - shiki.abe365.org
  become: true
  become_user: root
  gather_facts: yes
  ignore_unreachable: true
  vars:
    - github_account: toshibe678
    - runner_org: true
    - runner_labels: [self-hosted, linux, arm64]
    - access_token: "{{ crypt_github_org_access_token }}"
  roles:
    - role: monolithprojects.github_actions_runner
