---
- name: github self host runner setting
  hosts:
    - raspi.test
    - rasdev.test
#    - ranko.test
#    - sae.test
#    - kaede.test
#    - shiki.test
  become: true
  become_user: root
  gather_facts: yes
  ignore_unreachable: true
  vars:
    - github_account: toshibe678
    - runner_org: true
    - runner_labels: [self-hosted, linux, arm64]
    - access_token: "{{ crypt_github_org_access_token }}"
  roles:
    - role: monolithprojects.github_actions_runner
