all:
  children:
    linux:
      vars:
        ignore_unreachable: yes
        ansible_ssh_user: toshi
        ansible_ssh_port: 22
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      children:
        vpn:
          children:
            dev:
              hosts:
                vpn-dev.abe365.org: { }
            prod:
              hosts:
                vpn.toshi.click: { }
        monitoring:
          hosts:
            monitoring.abe365.org: { }
        # dockerで提供するので、docker系だけ入ればOK
        home_servers:
          hosts:
            dify.abe365.org: { }
            llm-proxy.abe365.org: { }
            develop.abe365.org: { }
            ai-test.abe365.org: { }
        k8s:
          hosts:
            k8s1.abe365.org: { }
            k8s2.abe365.org: { }
            k8s3.abe365.org: { }
        raspi:
          hosts:
            raspi.abe365.org: { }
            rasdev.abe365.org: { }
            sae.abe365.org: {}
            kaede.abe365.org: {}
            shiki.abe365.org: {}
            kako.abe365.org: {}           
    proxmox:
      hosts:
        shigure.abe365.org: { }
        infra1.abe365.org: { }
        infra2.abe365.org: { }
