---
- name: linux setting
  hosts: linux
  become: true
  become_user: root
  gather_facts: yes
  ignore_unreachable: true
  roles:
    - { name: ./inner_roles/common }
    - { name: ./inner_roles/docker }
    - { name: ./inner_roles/firewall }
    # - { name: prometheus.prometheus.node_exporter }
  # Linux機全体に適用する設定を記載する
  # 適宜Commonロールなどに分割すること
  tasks:
    - name: apt upgrade
      ansible.builtin.apt:
        upgrade: dist

    - name: Install power pkg
      ansible.builtin.package:
        name:
          - wireless-tools
          - pm-utils
        state: present

    - name: rc-local.service set
      template:
        src: "etc/systemd/system/rc-local.service"
        dest: "/etc/systemd/system/rc-local.service"
        owner: root
        group: root
        mode: 0644
        backup: true

    - name: rc.local set
      template:
        src: "etc/rc-local"
        dest: "/etc/rc.local"
        owner: root
        group: root
        mode: 0755
        backup: true

    - name: systemd set state rc-local.service
      systemd:
        name: rc-local
        state: restarted
        enabled: yes
        daemon_reload: yes



