---
collections:
 - name: prometheus.prometheus

# ansible-galaxy install -r requirements.yml -p roles --force
roles:
  - name: monolithprojects.github_actions_runner
    src: https://github.com/MonolithProjects/ansible-github_actions_runner

