---
- name: wireguard setting
  hosts:
    - vpn
  become: true
  become_user: root
  roles:
    - { name: ./dependency_roles/wireguard }

# cron
# */5 * * * * source /root/shell_file.sh && bash /home/toshi/scripts/shell/wireguard_check.sh
