name: Lint Ansible Templates

on:
  push:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible-*"
    branches:
      - main
      - develop

jobs:
  ansible-lint:
    runs-on: self-hosted
    container:
      image: ghcr.io/toshibe678/infra/ansible
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print the ansible lint Linter Version & run Linter.
        env:
          TOSHI_KEY: ${{ secrets.TOSHI_KEY }}
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: |
          cd ansible
          bash ./ci.sh
          ansible-playbook -i hosts_all.yml all.yml --syntax-check --vault-password-file ~/.ssh/.ansible_vault_pass -C
          rm -f ~/.ssh/id_rsa
          rm -f ~/.ssh/.ansible_vault_pass
