name: Cloudflare Terraform

on:
  workflow_dispatch:
  push:
    paths:
      - "cloudflere/**"
    branches:
      - main
      - develop

jobs:
  cloudflere:
    runs-on: self-hosted
    container:
      image: ghcr.io/toshibe678/infra/terraform:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      # - name: debug
      #   run: sleep 1000000
      # - name: configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::814229680634:role/GitHubActionsRole
          aws-region: ap-northeast-1
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./cloudflere
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./cloudflere
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Terraform apply
        id: apply
        run: terraform apply -no-color -auto-approve
        working-directory: ./cloudflere
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
