name: Terraform Docker image build and push

env:
  LANG: ja_JP.UTF-8

on:
  push:
    branches:
      - develop
    paths:
      - "docker/terraform/**"

jobs:
  terraform_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

#      - name: Prepare Build Arg
#        id: prepare_build_arg
#        run: |
#          CURRENT_TAG=${GITHUB_REF#refs/tags/}
#          echo ::set-output name=CURRENT_TAG::${CURRENT_TAG}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./docker/terraform
          file: ./docker/terraform/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/infra/terraform:latest
#            ghcr.io/${{ github.repository_owner }}/infra/terraform:${{ CURRENT_TAG }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
#          build-args: |
#            BUNDLER_VERSION=${{ steps.prepare_build_arg.outputs.BUNDLER_VERSION }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
